/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void testNotGoingToWork(){
    	Library classUnderTest = new Library();
        assertTrue("NotGoingToWork should return 'true'", !classUnderTest.notGoingToWork());
    }
    @Test public void testWord(){
    	Library classUnderTest = new Library();
        assertTrue("testWord should return 'true'", classUnderTest.word().equals("hello world"));
    }
    
//    "hello world";
}
